### ISSUE TITLE
Group Mapping Module not supporting multiple admin groups

### ISSUE THREAD

**Issue by ghost** [adfinis-sygroup/vault-playground#15]
https://github.com/adfinis/vault-playground/blob/f28848d45001977339af396ed92c3e688de962a2/docker/terraform/groups/main.tf#L19

Hey @in0rdr 

Unfortunately this is not going to work: If you put another group into [groups.yaml](https://github.com/adfinis/vault-playground/blob/f28848d45001977339af396ed92c3e688de962a2/docker/terraform/groups.yaml) with access/admin to the same namespace like `testgroup2`

```yaml
---

groups:
  testgroup:
    namespaces:
      tenant: {}
      tenant2: {}
      tenant3: {}
    metadata:
      owner: foo@bar.com
      cost_center: FooBar
  testgroup2:
    namespaces:
      tenant: {}
    metadata:
      owner: foo2@bar.com
```

it will break with `... reason=group already exists with path ...`. I wonder if you can fix this or if you are forced to wait for this feature to get implemented: https://github.com/hashicorp/terraform-provider-vault/issues/1371
